import { describe, expect, it } from 'vitest';
import { ExecutePlan } from './ExecutePlan.js';
import { ExecutionRunEntity } from '../../domain/execution/ExecutionRunEntity.js';
import { ExecutionRunRepository } from '../../infrastructure/execution/ExecutionRunRepository.js';
const engine = new ExecutePlan({} as any, {} as any, {} as any, {} as any, {} as any, {} as any, {} as any, {} as any, {} as any, {} as any, {} as any, {} as any);
describe('execution input snapshot', () => {
  it('records source lineage and redacts sensitive request material', () => { const snapshot = (engine as any).buildExecutionSnapshot({ operationId: 'op', datasetId: 'dataset', datasetRowReference: 'row-1', dependencies: [{ sourceOperationId: 'producer', sourceResponsePath: '$.id', targetRequestPath: '$.id' }] }, { environmentId: 'env', runtimeVariables: {}, environmentVariables: {}, datasetValues: {}, responses: {}, headers: {} }, { method: 'POST', url: 'https://x', headers: { Authorization: 'Bearer secret-token' }, body: { password: 'secret-value' } }, { email: { sourceType: 'DATASET', value: 'person@example.test', datasetId: 'dataset', rowId: 'row-1' }, token: { sourceType: 'RUNTIME', value: 'secret-value', variableName: 'token' } }); expect(snapshot.resolvedFields).toMatchObject([{ field: 'email', source: 'DATASET', reference: 'dataset' }, { field: 'token', source: 'RUNTIME', reference: 'token' }]); expect(JSON.stringify(snapshot)).not.toContain('secret-token'); expect(JSON.stringify(snapshot)).not.toContain('secret-value'); expect(snapshot.dependencies[0]).toMatchObject({ sourceOperationId: 'producer' }); });
  it('creates an immutable base snapshot identifier suitable for retries', () => { const make = () => (engine as any).buildExecutionSnapshot({}, { environmentId: 'env', runtimeVariables: {}, environmentVariables: {}, datasetValues: {}, responses: {}, headers: {} }, { method: 'GET', url: 'https://x', headers: {}, body: undefined }, {}); const snapshot = make(); expect(snapshot.baseSnapshotId).toBeTruthy(); expect(snapshot.request.method).toBe('GET'); });
  it('keeps secret references but never resolved secret values, and marks generators partial when no seed exists', () => { const snapshot = (engine as any).buildExecutionSnapshot({}, { environmentId: 'env', runtimeVariables: {}, environmentVariables: {}, datasetValues: {}, responses: {}, headers: {} }, { method: 'GET', url: 'https://x', headers: {}, body: undefined }, { key: { sourceType: 'SECRET', value: 'api-key-value', variableName: 'vault:payment-key' }, generated: { sourceType: 'GENERATED_VALUE', value: '123', variableName: 'uuid' } }); expect(snapshot.resolvedFields).toMatchObject([{ source: 'SECRET', reference: 'vault:payment-key' }, { source: 'GENERATOR', reproducibility: { status: 'PARTIAL' } }]); expect(JSON.stringify(snapshot)).not.toContain('api-key-value'); });
  it('persists and reloads an unchanged sanitized snapshot despite later source changes', async () => { const repo = new ExecutionRunRepository(); const id = `snapshot-${Date.now()}`; const snapshot = (engine as any).buildExecutionSnapshot({ requirementId: 'req', operationId: 'op', datasetId: 'dataset' }, { environmentId: 'env', runtimeVariables: {}, environmentVariables: {}, datasetValues: {}, responses: {}, headers: {} }, { method: 'GET', url: 'https://x', headers: { Authorization: 'Bearer hidden' }, body: { password: 'hidden' } }, {}); const run = new ExecutionRunEntity(id, `snapshot-project-${Date.now()}`, 'req', 'plan', 'StopOnFailure', 'Completed', { environmentId: 'env', baseUrl: 'https://x', environmentVariables: {}, datasetValues: {}, runtimeVariables: {}, responses: {}, headers: {} }, [{ stepId: 'step', executionOrder: 1, status: 'Passed', request: { method: 'GET', url: 'https://x', headers: {} }, response: null, assertions: [], capturedVariables: {}, error: null, startedAt: 1, completedAt: 2, validations: [], executionSnapshot: snapshot }], [], { totalSteps: 1, passed: 1, failed: 0, skipped: 0, blocked: 0, duration: 1, validationPassed: 0, validationFailed: 0, validationWarnings: 0 }, 1, 1, 2); await repo.create(run); const reloaded = await new ExecutionRunRepository().findById(id); expect(reloaded?.stepResults[0]?.executionSnapshot).toEqual(snapshot); expect(JSON.stringify(reloaded)).not.toContain('hidden'); await repo.delete(id); });
});
