import React from 'react';
import { ArrowRight, BookOpen, Check, Code2, LifeBuoy, Rocket, ShieldCheck, Sparkles, Users, Workflow } from 'lucide-react';
import { useLandingAuth } from '../context/LandingAuthContext';

const SOLUTIONS = [
  { icon: Code2, title: 'For engineering teams', description: 'Turn API contracts into maintainable validation coverage without hand-writing every test path.', points: ['OpenAPI, Postman, and GraphQL imports', 'Request-aware assertions and scripts', 'Fast feedback before merge or release'] },
  { icon: Users, title: 'For QA and platform teams', description: 'Standardize quality workflows across services, environments, and teams from one shared workspace.', points: ['Reusable test strategies and suites', 'Dependency-aware execution plans', 'Audit trails, reports, and ownership'] },
  { icon: ShieldCheck, title: 'For growing organizations', description: 'Make quality repeatable as your API estate grows, with controls that keep teams aligned and data isolated.', points: ['Project and organization isolation', 'Environment and test-data controls', 'Risk signals for release decisions'] },
];

const WORKFLOW = [
  ['01', 'Import your contract', 'Bring in an OpenAPI, Postman, GraphQL, or environment file.'],
  ['02', 'Map the quality model', 'TestForge identifies operations, dependencies, auth flows, and data needs.'],
  ['03', 'Generate coverage', 'Create requirements, test designs, assertions, and an executable plan.'],
  ['04', 'Run and improve', 'Execute validations, inspect failures, and share a developer-ready report.'],
];

const PLANS = [
  { name: 'Starter', eyebrow: 'For individual builders', description: 'Explore AI-assisted API quality for a focused project.', price: 'Free', points: ['1 project workspace', 'Contract import and API explorer', 'AI-assisted test planning', 'Execution and report basics'] },
  { name: 'Team', eyebrow: 'For quality-focused teams', description: 'Coordinate API quality from discovery through release.', price: 'Built for teams', points: ['Shared projects and environments', 'Test data and reusable suites', 'Dependency-aware execution', 'Audit history and richer reports'], featured: true },
  { name: 'Scale', eyebrow: 'For platform organizations', description: 'Bring governance, automation, and visibility to every service.', price: 'Talk to us', points: ['Organization-wide workflows', 'Advanced access and integrations', 'Scheduled validation pipelines', 'Priority guidance and support'] },
];

const RESOURCES = [
  { icon: Rocket, title: 'Five-minute quickstart', description: 'Import your first API, choose an environment, and run a quality workflow.' },
  { icon: BookOpen, title: 'API quality guide', description: 'Learn how contracts, requirements, test design, and execution fit together.' },
  { icon: LifeBuoy, title: 'Implementation support', description: 'Get practical guidance for teams moving from scripts to a quality system.' },
];

const INSIGHTS = [
  { category: 'API quality', title: 'From endpoint checks to quality engineering', description: 'Why durable API confidence requires context, dependencies, and meaningful assertions.' },
  { category: 'Workflow', title: 'Designing an execution plan that reflects reality', description: 'How authentication, data, and service relationships shape reliable validation.' },
  { category: 'Platform', title: 'A shared source of truth for test readiness', description: 'Bring contracts, environments, test data, and reports into one workflow.' },
];

export const LandingOverviewSections: React.FC = () => {
  const { openRegister } = useLandingAuth();
  return <>
    <section id="solutions" className="relative z-10 border-t border-border py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Built for the whole quality lifecycle</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-text sm:text-4xl">One workspace for every API quality conversation.</h2><p className="mt-4 text-lg leading-relaxed text-text-secondary">From the first contract import to the final release decision, TestForge keeps technical context connected and actionable.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{SOLUTIONS.map((solution) => <article key={solution.title} className="theme-glass-card rounded-2xl border p-6"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/15 text-primary"><solution.icon className="h-5 w-5" /></div><h3 className="mt-5 text-xl font-semibold text-text">{solution.title}</h3><p className="mt-2 text-sm leading-relaxed text-text-secondary">{solution.description}</p><ul className="mt-5 space-y-3 text-sm text-text-secondary">{solution.points.map((point) => <li key={point} className="flex gap-2"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{point}</li>)}</ul></article>)}</div><div className="landing-surface mt-8 rounded-2xl border p-6 lg:p-8"><div className="flex items-center gap-2 text-sm font-semibold text-primary"><Workflow className="h-4 w-4" />How the workflow comes together</div><div className="mt-6 grid gap-6 md:grid-cols-4">{WORKFLOW.map(([number, title, description]) => <div key={number}><span className="text-xs font-semibold tracking-[0.18em] text-primary">{number}</span><h3 className="mt-2 font-semibold text-text">{title}</h3><p className="mt-2 text-sm leading-relaxed text-text-secondary">{description}</p></div>)}</div></div></div></section>
    <section id="pricing" className="relative z-10 border-t border-border py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Simple path to adoption</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-text sm:text-4xl">Start small. Scale quality with confidence.</h2><p className="mt-4 text-lg text-text-secondary">Choose the level of collaboration your team needs today. Your workflows stay familiar as your quality program grows.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{PLANS.map((plan) => <article key={plan.name} className={`theme-glass-card rounded-2xl border p-6 ${plan.featured ? 'border-primary/70 ring-1 ring-primary/30' : ''}`}>{plan.featured && <span className="inline-flex rounded-full bg-primary/15 px-3 py-1 text-xs font-semibold text-primary">Most popular</span>}<p className="mt-3 text-xs font-semibold uppercase tracking-[0.16em] text-text-secondary">{plan.eyebrow}</p><h3 className="mt-2 text-2xl font-semibold text-text">{plan.name}</h3><p className="mt-3 min-h-12 text-sm leading-relaxed text-text-secondary">{plan.description}</p><p className="mt-6 text-xl font-semibold text-primary">{plan.price}</p><ul className="mt-6 space-y-3 border-t border-border pt-5 text-sm text-text-secondary">{plan.points.map((point) => <li key={point} className="flex gap-2"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{point}</li>)}</ul><button type="button" onClick={openRegister} className={`${plan.featured ? 'landing-primary-action text-white' : 'landing-secondary-action border text-text'} mt-8 inline-flex w-full items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold`}>{plan.featured ? 'Start free' : 'Explore TestForge'}<ArrowRight className="h-4 w-4" /></button></article>)}</div></div></section>
    <section id="docs" className="relative z-10 border-t border-border py-24"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[0.85fr_1.15fr] lg:items-center lg:px-8"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Documentation & enablement</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-text sm:text-4xl">Clear answers from first import to first report.</h2><p className="mt-4 text-lg leading-relaxed text-text-secondary">Understand the product model, connect your existing API workflow, and give every teammate a clear next step.</p><button type="button" onClick={openRegister} className="landing-primary-action mt-8 inline-flex items-center gap-2 rounded-xl px-5 py-3 text-sm font-semibold text-white">Open the workspace <ArrowRight className="h-4 w-4" /></button></div><div className="grid gap-4 sm:grid-cols-3">{RESOURCES.map((resource) => <article key={resource.title} className="theme-glass-card rounded-2xl border p-5"><resource.icon className="h-5 w-5 text-primary" /><h3 className="mt-5 font-semibold text-text">{resource.title}</h3><p className="mt-2 text-sm leading-relaxed text-text-secondary">{resource.description}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-primary">Learn more <ArrowRight className="h-3 w-3" /></span></article>)}</div></div></section>
    <section id="blog" className="relative z-10 border-t border-border py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Ideas for better validation</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-text sm:text-4xl">Practical insight for modern API teams.</h2></div><a href="#docs" className="inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline">Visit the guide <ArrowRight className="h-4 w-4" /></a></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{INSIGHTS.map((insight) => <article key={insight.title} className="theme-glass-card rounded-2xl border p-6"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-primary"><Sparkles className="h-3.5 w-3.5" />{insight.category}</div><h3 className="mt-5 text-xl font-semibold text-text">{insight.title}</h3><p className="mt-3 text-sm leading-relaxed text-text-secondary">{insight.description}</p><a href="#docs" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline">Read the perspective <ArrowRight className="h-4 w-4" /></a></article>)}</div></div></section>
  </>;
};

export default LandingOverviewSections;
