import { randomUUID } from 'node:crypto';
import { existsSync, mkdirSync } from 'node:fs'; import { join } from 'node:path';
import type { DurableJob, DurableJobRepository } from '../../domain/jobs/DurableJob.js';
import { readJsonArray, updateJsonArray } from '../persistence/JsonFileStore.js';
import { sensitiveDataRedactor } from '../security/SensitiveDataRedactionService.js';
export class JsonDurableJobRepository implements DurableJobRepository {
  private file = join(process.cwd(), 'data', 'runtime', 'jobs.json'); private ensure() { const d = join(process.cwd(), 'data', 'runtime'); if (!existsSync(d)) mkdirSync(d, { recursive: true }); }
  async enqueue(job: DurableJob) { this.ensure(); let result: DurableJob = job; await updateJsonArray<DurableJob>(this.file, [], (all) => { const existing = all.find((x) => x.idempotencyKey === job.idempotencyKey); if (existing) result = existing; else all.push(job); return all; }); return result; }
  async claim(workerId: string, leaseMs: number, types?: string[]): Promise<DurableJob | null> { let result: DurableJob | null = null; await updateJsonArray<DurableJob>(this.file, [], (all) => { const now = Date.now(); const job = all.find((x) => (x.status === 'QUEUED' || (x.status === 'RUNNING' && (x.leaseExpiresAt || 0) <= now)) && (!types || types.includes(x.jobType))); if (!job) return all; job.status = 'RUNNING'; job.startedAt ||= now; job.attempt += 1; job.leaseOwner = workerId; job.leaseExpiresAt = now + leaseMs; result = { ...job, payload: { ...job.payload } }; return all; }); return result as DurableJob | null; }
  async acknowledge(id:string, owner:string) { return this.update(id, owner, (x) => { x.status='SUCCEEDED'; x.completedAt=Date.now(); x.leaseOwner=null; x.leaseExpiresAt=null; }); }
  async fail(id:string, owner:string, error:Record<string,unknown>) { return this.update(id, owner, (x) => { x.error=sensitiveDataRedactor.redact(error); x.leaseOwner=null; x.leaseExpiresAt=null; x.status=x.attempt < x.maxAttempts ? 'QUEUED':'FAILED'; if(x.status==='FAILED') x.completedAt=Date.now(); }); }
  async renewLease(id:string, owner:string, ms:number) { return this.update(id, owner, (x)=>{x.leaseExpiresAt=Date.now()+ms;}); }
  async updatePayload(id:string, owner:string, payload:Record<string,unknown>) { return this.update(id, owner, (x)=>{x.payload=sensitiveDataRedactor.redact(payload) as Record<string, unknown>;}); }
  async cancel(id:string) { let result:DurableJob|undefined; await updateJsonArray<DurableJob>(this.file, [], (all) => { const j=all.find(x=>x.jobId===id); if(!j) throw new Error(`Job ${id} not found`); if(j.status==='SUCCEEDED') throw new Error('Completed jobs cannot be cancelled'); j.status='CANCELLED'; j.completedAt=Date.now(); j.leaseOwner=null; j.leaseExpiresAt=null; result=j; return all; }); return result!; }
  async findById(id:string){return (await this.all()).find(x=>x.jobId===id)||null;} async list(f:any={}){return (await this.all()).filter(x=>Object.entries(f).every(([k,v])=>!v||(x as any)[k]===v));}
  private async update(id:string,owner:string,fn:(x:DurableJob)=>void){let result:DurableJob|undefined;await updateJsonArray<DurableJob>(this.file, [], (all) => {const j=all.find(x=>x.jobId===id);if(!j)throw new Error(`Job ${id} not found`);if(j.leaseOwner!==owner||j.status!=='RUNNING')throw new Error('Job lease is not owned by this worker');fn(j);result=j;return all;});return result!;} private async all(){this.ensure();return readJsonArray<DurableJob>(this.file);}
}
export function newJob(input: Omit<DurableJob,'jobId'|'status'|'createdAt'|'startedAt'|'completedAt'|'attempt'|'error'|'leaseOwner'|'leaseExpiresAt'>):DurableJob{return{...input,jobId:randomUUID(),status:'QUEUED',createdAt:Date.now(),startedAt:null,completedAt:null,attempt:0,error:null,leaseOwner:null,leaseExpiresAt:null};}
