import { describe, expect, it } from 'vitest';
import { selectByBudget, resolveBudget } from './GenerationBudget.js';
const design = (id: string, patch: any = {}) => ({ id, title: id, operationId: 'op-1', acceptanceCriterionId: 'ac-1', scenarioId: id, priority: 'Low', mappingState: 'confirmed', mappingConfidence: 90, testCaseType: 'Negative', mutationProvenance: { strategy: 'type-violation', fieldPath: '$.x', location: 'body' }, ...patch });
describe('GenerationBudget', () => {
  it('uses bounded safe defaults', () => expect(resolveBudget()).toMatchObject({ maxTotalScenarios: 30, maxMutationsPerOperationField: 3 }));
  it('enforces total limit and deterministic high-risk order', () => { const r = selectByBudget([design('low', { mutationProvenance: { fieldPath: '$.low' } }), design('high', { priority: 'High', mutationProvenance: { fieldPath: '$.high' } }), design('medium', { priority: 'Medium', mutationProvenance: { fieldPath: '$.medium' } })] as any, { maxTotalScenarios: 2, allocation: { negative: 2, positive: 0, edge: 0 } }); expect(r.selected.map(x => x.design.id)).toEqual(['high', 'medium']); expect(r.omitted[0].reason).toBe('BUDGET_LIMIT_REACHED'); });
  it('honours family allocation, duplicate suppression, security and boundary priority', () => { const r = selectByBudget([design('positive', { testCaseType: 'Positive' }), design('dup'), design('dup2'), design('security', { testCaseType: 'Security', priority: 'High', mutationProvenance: { strategy: 'boundary', fieldPath: '$.token', location: 'header' } })] as any, { maxTotalScenarios: 4, allocation: { positive: 1, negative: 1, edge: 1 } }); expect(r.selected.map(x => x.design.id)).toContain('security'); expect(r.omitted.some(x => x.reason === 'DUPLICATE')).toBe(true); });
  it('does not include sensitive payload values in decision metadata', () => { const r = selectByBudget([design('safe', { requestOverrides: { body: { password: 'secret' } } })] as any); expect(JSON.stringify(r.selected[0].decision)).not.toContain('secret'); });
});
