import type { TestDesignEntity } from '../../domain/requirements/TestDesignEntity.js';

export interface GenerationBudget { maxTotalScenarios?: number; maxMutationsPerOperationField?: number; allocation?: { positive?: number; negative?: number; edge?: number }; riskPriority?: 'HIGH_FIRST' | 'BALANCED'; prioritizeBoundary?: boolean; includeAuthSecurity?: boolean; suppressDuplicates?: boolean; }
export interface ResolvedGenerationBudget { maxTotalScenarios: number; maxMutationsPerOperationField: number; allocation: { positive: number; negative: number; edge: number }; riskPriority: 'HIGH_FIRST' | 'BALANCED'; prioritizeBoundary: boolean; includeAuthSecurity: boolean; suppressDuplicates: boolean; }
export type BudgetOmissionReason = 'BUDGET_LIMIT_REACHED' | 'LOWER_RISK_PRIORITY' | 'DUPLICATE' | 'UNSUPPORTED_CONSTRUCT' | 'MISSING_TEST_DATA' | 'MAPPING_UNRESOLVED' | 'SAFETY_RESTRICTION';
export interface BudgetDecision { selected: boolean; riskScore: number; reason: string; budget: ResolvedGenerationBudget; omissions?: Array<{ scenarioId: string; family: string; reason: BudgetOmissionReason }>; }
export const resolveBudget = (budget: GenerationBudget = {}): ResolvedGenerationBudget => ({ maxTotalScenarios: Math.max(1, budget.maxTotalScenarios ?? 30), maxMutationsPerOperationField: Math.max(1, budget.maxMutationsPerOperationField ?? 3), allocation: { positive: budget.allocation?.positive ?? 10, negative: budget.allocation?.negative ?? 14, edge: budget.allocation?.edge ?? 6 }, riskPriority: budget.riskPriority ?? 'HIGH_FIRST', prioritizeBoundary: budget.prioritizeBoundary ?? true, includeAuthSecurity: budget.includeAuthSecurity ?? true, suppressDuplicates: budget.suppressDuplicates ?? true });
const family = (d: TestDesignEntity) => d.testCaseType === 'Positive' ? 'positive' : d.testCaseType === 'Security' ? 'edge' : d.mutationProvenance?.strategy === 'boundary' ? 'edge' : 'negative';
export function selectByBudget(designs: TestDesignEntity[], config?: GenerationBudget) {
  const budget = resolveBudget(config); const omitted: BudgetDecision['omissions'] = []; const seen = new Set<string>(); const perField = new Map<string, number>(); const allocations = { ...budget.allocation };
  const ranked = designs.map((design, index) => { const risk = (design.priority === 'High' ? 40 : design.priority === 'Medium' ? 20 : 5) + (design.testCaseType === 'Security' ? 30 : 0) + (design.mutationProvenance?.strategy === 'boundary' && budget.prioritizeBoundary ? 20 : 0) + (!design.operationId || design.mappingState === 'unmapped' ? -10 : 10) + Math.round((100 - design.mappingConfidence) / 10); return { design, index, risk, family: family(design) }; }).sort((a,b) => b.risk - a.risk || a.design.title.localeCompare(b.design.title) || a.index - b.index);
  const selected: Array<{ design: TestDesignEntity; decision: BudgetDecision }> = [];
  for (const candidate of ranked) { const key = `${candidate.design.operationId}|${candidate.design.acceptanceCriterionId || ''}|${candidate.design.mutationProvenance?.fieldPath || candidate.design.title}`; const fieldKey = `${candidate.design.operationId}|${candidate.design.mutationProvenance?.fieldPath || ''}`; let reason: BudgetOmissionReason | undefined;
    if (!budget.includeAuthSecurity && candidate.design.testCaseType === 'Security') reason = 'SAFETY_RESTRICTION'; else if (!candidate.design.operationId) reason = 'MAPPING_UNRESOLVED'; else if (budget.suppressDuplicates && seen.has(key)) reason = 'DUPLICATE'; else if ((perField.get(fieldKey) || 0) >= budget.maxMutationsPerOperationField) reason = 'BUDGET_LIMIT_REACHED'; else if (selected.length >= budget.maxTotalScenarios) reason = 'BUDGET_LIMIT_REACHED'; else if ((allocations as any)[candidate.family] <= 0) reason = 'LOWER_RISK_PRIORITY';
    if (reason) { omitted.push({ scenarioId: candidate.design.scenarioId || candidate.design.id, family: candidate.family, reason }); continue; }
    seen.add(key); perField.set(fieldKey, (perField.get(fieldKey) || 0) + 1); (allocations as any)[candidate.family]--; selected.push({ design: candidate.design, decision: { selected: true, riskScore: candidate.risk, reason: 'Selected by deterministic risk priority.', budget } });
  }
  return { selected, omitted, budget };
}
