import { describe, expect, it, vi } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os'; import { join } from 'node:path';
import { GenerateTestDesignWithAI } from './GenerateTestDesignWithAI.js';
import { GenerationProvenanceService } from './GenerationProvenanceService.js';
import { TestCaseVersionService } from './TestCaseVersionService.js';
import { RequirementEntity } from '../../domain/requirements/RequirementEntity.js';
import { ApiOperationEntity } from '../../domain/api/ApiOperationEntity.js';
const req = new RequirementEntity('req', 'project', 'Create order', 'description', 'Functional', 80, 'Manual', null, 'Reviewed', 'Approved', ['op'], [], [], [{ id: 'ac', text: 'works' }], 1, 2);
const op = new ApiOperationEntity('op', 'project', 'service', 'create', 'POST', '/orders', '', 'None', 'Active', 1, 2);
function harness(outputs: Array<any>) { const rows: any[] = []; const root = mkdtempSync(join(tmpdir(), 'tf-ai-')); const storage = join(root, 'versions.json'); const versions = new TestCaseVersionService(storage); const designs: any = { create: async (d: any) => (rows.push(d), d), update: async (id: string, p: any) => { Object.assign(rows.find(x => x.id === id), p); return rows.find(x => x.id === id); }, findByRequirement: async () => rows, delete: async (id: string) => { const i = rows.findIndex(x => x.id === id); if (i >= 0) rows.splice(i, 1); } }; const provenance = new GenerationProvenanceService({ findByProject: async () => [op] } as any, { findByProject: async () => [] } as any, designs, versions); const manager: any = { getProvider: async () => ({ id: 'provider', name: 'OpenAI', provider: 'OpenAI', model: 'gpt-test', enabled: true }), generate: vi.fn(async () => { const next = outputs.shift(); if (next instanceof Error) throw next; return { content: next, model: 'gpt-test', usage: { totalTokens: 1 }, cost: { totalCost: 0 } }; }) }; const usecase = new GenerateTestDesignWithAI({ findById: async () => req } as any, { findByRequirement: async () => null } as any, designs, { buildContext: async () => ({ apiOperations: [op], environments: [], datasets: [] }) } as any, { previewPrompt: async () => ({ systemPrompt: 's', userPrompt: 'u', tokenEstimate: 1, validationWarnings: [] }) } as any, manager, {} as any, undefined, provenance); return { usecase, manager, versions, storage, root }; }
const valid = JSON.stringify({ designs: [{ title: 'valid', operationId: 'op', acceptanceCriterionId: 'ac', assertions: [{ type: 'status', operator: 'equals', path: '$.status', expected: 200 }] }] });
describe('GenerateTestDesignWithAI persisted provenance', () => {
  it('keeps requirement-derived designs unmapped even when AI returns an operation id', async () => {
    const h = harness([valid]);
    const result = await h.usecase.execute({ projectId: 'project', requirementId: 'req', providerId: 'provider', budget: { maxTotalScenarios: 1 } });
    expect(result.designs[0]).toMatchObject({ operationId: '', environmentId: '', datasetId: '', mappingState: 'unmapped', mappingConfidence: 0 });
    expect(result.warnings).toContain('1 AI-supplied operation mapping(s) were ignored. Endpoint mapping is performed separately.');
    rmSync(h.root, { recursive: true, force: true });
  });

  it('persists attempt-two valid AI provenance and reloads unchanged', async () => { const h = harness(['bad', valid]); const result = await h.usecase.execute({ projectId: 'project', requirementId: 'req', providerId: 'provider', budget: { maxTotalScenarios: 1 } }); const p = result.designs[0].generationProvenance; expect(h.manager.generate).toHaveBeenCalledTimes(2); expect(p).toMatchObject({ mode: 'AI_GENERATED', ai: { providerId: 'provider', model: 'gpt-test', attempts: 2, validationStatus: 'VALID' } }); expect(result.designs).toHaveLength(1); const old = h.versions.reviewQueue('project')[0].version; const reloaded = new TestCaseVersionService(h.storage).current(old.testCaseId); expect(reloaded.content.generationProvenance).toEqual(p); rmSync(h.root, { recursive: true, force: true }); });
  it('persists malformed exhaustion as fallback without AI attribution and observes budget', async () => { const h = harness(['bad', 'bad']); const result = await h.usecase.execute({ projectId: 'project', requirementId: 'req', providerId: 'provider', budget: { maxTotalScenarios: 1 } }); const p = result.designs[0]!.generationProvenance!; expect(h.manager.generate).toHaveBeenCalledTimes(2); expect(result.designs).toHaveLength(1); expect(p).toMatchObject({ mode: 'FALLBACK' }); expect(p.ai).toBeUndefined(); expect(JSON.stringify(p)).not.toContain('gpt-test'); rmSync(h.root, { recursive: true, force: true }); });
  it('persists sanitized fallback after provider failures', async () => { const h = harness([new Error('token=secret raw response'), new Error('token=secret raw response')]); const result = await h.usecase.execute({ projectId: 'project', requirementId: 'req', providerId: 'provider', budget: { maxTotalScenarios: 1 } }); expect(h.manager.generate).toHaveBeenCalledTimes(2); const p = result.designs[0]!.generationProvenance!; expect(p).toMatchObject({ mode: 'FALLBACK' }); expect(p.ai).toBeUndefined(); expect(JSON.stringify(p)).not.toContain('secret'); expect(JSON.stringify(p)).not.toContain('gpt-test'); rmSync(h.root, { recursive: true, force: true }); });
});
