import { describe, expect, it } from 'vitest';
import { TestCaseVersionService } from './TestCaseVersionService.js';

const candidate = (payload = { name: 'a' }, assertions: unknown = [{ status: 200 }]) => ({ requirementId: 'req', acceptanceCriterionId: 'ac-1', operationId: 'op-1', scenarioIntent: 'create user', payload, assertions, mapping: { operationId: 'op-1' }, mutationProvenance: { strategy: 'boundary', fieldPath: '$.name' } });
describe('TestCaseVersionService', () => {
  it('keeps stable identity and unchanged version across regeneration', () => { const s = new TestCaseVersionService(); const first = s.reconcile('p', [candidate()])[0]; const second = s.reconcile('p', [candidate()])[0]; expect(second.testCaseId).toBe(first.testCaseId); expect(second.id).toBe(first.id); expect(s.history(first.testCaseId)).toHaveLength(1); });
  it('creates a review-required immutable version for changed executable content', () => { const s = new TestCaseVersionService(); const first = s.reconcile('p', [candidate()])[0]; s.review(first.id, 'APPROVED', 'reviewer'); const next = s.reconcile('p', [candidate({ name: 'b' })])[0]; expect(next.testCaseId).toBe(first.testCaseId); expect(next.version).toBe(2); expect(next.lifecycle).toBe('REVIEW_REQUIRED'); expect(s.getVersion(first.id).lifecycle).toBe('APPROVED'); });
  it('applies approval/rejection/deprecation to the exact version and exposes traceability', () => { const s = new TestCaseVersionService(); const v = s.reconcile('p', [candidate()])[0]; s.review(v.id, 'REJECTED', 'r', 'invalid'); expect(s.getVersion(v.id)).toMatchObject({ lifecycle: 'REJECTED', reviewer: 'r', reviewReason: 'invalid' }); s.review(v.id, 'DEPRECATED', 'r'); expect(s.trace(v.id, 'run-1')).toMatchObject({ requirementId: 'req', acceptanceCriterionId: 'ac-1', testCaseId: v.testCaseId, operationId: 'op-1', executionRunId: 'run-1' }); });
  it('reconciles duplicate candidates without deleting history', () => { const s = new TestCaseVersionService(); expect(s.reconcile('p', [candidate(), candidate()])).toHaveLength(1); });
  it('filters review queue, creates immutable manual edits, and calculates protocol-neutral coverage', () => { const s = new TestCaseVersionService(); const first = s.reconcile('p', [candidate()])[0]; const edited = s.edit(first.id, { payload: { name: 'manual' }, protocol: 'graphql', operationLabel: 'mutation CreateUser' }); expect(edited.lifecycle).toBe('REVIEW_REQUIRED'); expect(s.reviewQueue('p', 'REVIEW_REQUIRED')[0].view.operation).toMatchObject({ protocol: 'graphql', label: 'mutation CreateUser' }); expect(s.coverage('p')).toMatchObject({ acceptanceCriteriaCovered: 1, operationsCovered: 1 }); expect(s.diff(first.id, edited.id).map((d) => d.field)).toContain('payload'); });
  it('performs exact-version bulk review without approving a newer version', () => { const s = new TestCaseVersionService(); const first = s.reconcile('p', [candidate()])[0]; const next = s.edit(first.id, { assertions: [{ status: 201 }] }); s.bulk('p', [first.id], 'APPROVED', 'reviewer'); expect(s.getVersion(first.id).lifecycle).toBe('APPROVED'); expect(s.getVersion(next.id).lifecycle).toBe('REVIEW_REQUIRED'); });
});
