import { writeJsonFileSyncAtomic } from '../../infrastructure/persistence/JsonFileStore.js';
import { createHash, randomUUID } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { TestCaseEntity, TestCaseVersionEntity, type TestCaseLifecycle, type TestCaseVersionContent } from '../../domain/test-case/TestCaseEntity.js';
import { calculateCoverage, type CoverageScope } from './CoverageModel.js';

export class TestCaseVersionService {
  private cases = new Map<string, TestCaseEntity>(); private versions = new Map<string, TestCaseVersionEntity>(); private suiteMembership = new Map<string, Array<{ testCaseId: string; testCaseVersionId: string }>>();
  private readonly storagePath: string | null;
  constructor(storagePath?: string) { this.storagePath = storagePath ?? (process.env.NODE_ENV === 'test' ? null : join(process.cwd(), 'data', 'runtime', 'test-case-versions.json')); this.restore(); }
  fingerprint(content: TestCaseVersionContent): string { return createHash('sha256').update(JSON.stringify({ requirementId: content.requirementId, acceptanceCriterionId: content.acceptanceCriterionId, operationId: content.operationId, scenarioIntent: content.scenarioIntent, mutationProvenance: content.mutationProvenance })).digest('hex'); }
  reconcile(projectId: string, candidates: TestCaseVersionContent[]): TestCaseVersionEntity[] { const output: TestCaseVersionEntity[] = []; const seen = new Set<string>(); for (const content of candidates) { const fp = this.fingerprint(content); if (seen.has(fp)) continue; seen.add(fp); let tc = [...this.cases.values()].find((item) => item.projectId === projectId && item.fingerprint === fp); if (!tc) { const id = randomUUID(); const v = this.newVersion(id, 1, content, 'GENERATED'); tc = new TestCaseEntity(id, projectId, fp, v.id, Date.now(), Date.now()); this.cases.set(id, tc); this.versions.set(v.id, v); output.push(v); continue; } const current = this.versions.get(tc.currentVersionId)!; if (JSON.stringify(this.withoutCoverage(current.content)) === JSON.stringify(this.withoutCoverage(content))) { output.push(current); continue; } const v = this.newVersion(tc.id, current.version + 1, content, 'REVIEW_REQUIRED'); tc.currentVersionId = v.id; tc.updatedAt = Date.now(); this.versions.set(v.id, v); output.push(v); } this.persist(); return output; }
  ingest(projectId: string, candidates: TestCaseVersionContent[]): TestCaseVersionEntity[] { return this.reconcile(projectId, candidates); }
  review(versionId: string, lifecycle: 'APPROVED' | 'REJECTED' | 'DEPRECATED', reviewer: string, reason?: string): TestCaseVersionEntity { const v = this.getVersion(versionId); v.lifecycle = lifecycle; v.reviewer = reviewer; v.reviewedAt = Date.now(); v.reviewReason = reason; this.persist(); return v; }
  getVersion(id: string): TestCaseVersionEntity { const v = this.versions.get(id); if (!v) throw new Error(`Test case version ${id} not found`); return v; }
  history(testCaseId: string): TestCaseVersionEntity[] { return [...this.versions.values()].filter((v) => v.testCaseId === testCaseId).sort((a,b) => a.version-b.version); }
  current(testCaseId: string): TestCaseVersionEntity { const tc = this.cases.get(testCaseId); if (!tc) throw new Error(`Test case ${testCaseId} not found`); return this.getVersion(tc.currentVersionId); }
  trace(versionId: string, runId?: string) { const v = this.getVersion(versionId); return { requirementId: v.content.requirementId, acceptanceCriterionId: v.content.acceptanceCriterionId, testCaseId: v.testCaseId, testCaseVersionId: v.id, version: v.version, operationId: v.content.operationId, executionRunId: runId, generationProvenance: v.content.generationProvenance, coverage: v.content.coverage }; }
  reviewQueue(projectId: string, lifecycle?: TestCaseLifecycle, filters: Record<string, unknown> = {}) { return [...this.cases.values()].filter((tc) => tc.projectId === projectId).map((tc) => ({ testCase: tc, version: this.current(tc.id), view: this.reviewView(this.current(tc.id)) })).filter((item) => !lifecycle || item.version.lifecycle === lifecycle).filter((item: any) => (!filters.requirementId || item.version.content.requirementId === filters.requirementId) && (!filters.acceptanceCriterionId || item.version.content.acceptanceCriterionId === filters.acceptanceCriterionId) && (!filters.operationId || item.version.content.operationId === filters.operationId) && (!filters.operationRisk || item.view.operation.risk === filters.operationRisk) && (!filters.mappingStatus || item.view.mapping?.state === filters.mappingStatus) && (!filters.mappingConfidence || Number(item.view.mapping?.confidence) >= Number(filters.mappingConfidence)) && (!filters.mutationStrategy || item.version.content.mutationProvenance?.strategy === filters.mutationStrategy)); }
  edit(versionId: string, patch: Partial<TestCaseVersionContent>): TestCaseVersionEntity { const current = this.getVersion(versionId); const tc = this.cases.get(current.testCaseId)!; const content = { ...structuredClone(current.content), ...structuredClone(patch) }; if (JSON.stringify(content) === JSON.stringify(current.content)) return current; delete (content as any).coverage; const next = this.newVersion(tc.id, current.version + 1, content, 'REVIEW_REQUIRED'); tc.currentVersionId = next.id; tc.updatedAt = Date.now(); this.versions.set(next.id, next); this.persist(); return next; }
  bulk(projectId: string, versionIds: string[], action: 'APPROVED' | 'REJECTED' | 'DEPRECATED', reviewer: string, reason?: string) { return versionIds.map((id) => { try { this.assertVersionProject(id, projectId); const version = this.getVersion(id); if (action === 'APPROVED' && (!version.content.operationId || (version.content.mapping as any)?.state === 'review')) return { versionId: id, status: 'ineligible', reason: !version.content.operationId ? 'unresolved operation' : 'mapping review required' }; return { versionId: id, status: 'succeeded', version: this.review(id, action, reviewer, reason) }; } catch (error) { return { versionId: id, status: 'other validation reason', reason: error instanceof Error ? error.message : String(error) }; } }); }
  deleteByProject(projectId: string): { testCases: number; versions: number } {
    const testCaseIds = [...this.cases.values()]
      .filter((testCase) => testCase.projectId === projectId)
      .map((testCase) => testCase.id);
    const testCaseIdSet = new Set(testCaseIds);
    const versionIds = [...this.versions.values()]
      .filter((version) => testCaseIdSet.has(version.testCaseId))
      .map((version) => version.id);

    for (const testCaseId of testCaseIds) this.cases.delete(testCaseId);
    for (const versionId of versionIds) this.versions.delete(versionId);
    for (const [suiteId, members] of this.suiteMembership) {
      const remaining = members.filter((member) => !testCaseIdSet.has(member.testCaseId));
      if (remaining.length > 0) this.suiteMembership.set(suiteId, remaining);
      else this.suiteMembership.delete(suiteId);
    }
    this.persist();
    return { testCases: testCaseIds.length, versions: versionIds.length };
  }
  addToSuite(projectId: string, suiteId: string, versionIds: string[]) { const members = this.suiteMembership.get(suiteId) || []; const results = versionIds.map((id) => { try { this.assertVersionProject(id, projectId); const v = this.getVersion(id); if (v.lifecycle !== 'APPROVED') return { versionId: id, status: 'ineligible', reason: 'version is not approved' }; if (!v.content.operationId || (v.content.mapping as any)?.state === 'review') return { versionId: id, status: 'ineligible', reason: 'unresolved operation or mapping review required' }; if (members.some((m) => m.testCaseId === v.testCaseId && m.testCaseVersionId === v.id)) return { versionId: id, status: 'ineligible', reason: 'already in suite' }; members.push({ testCaseId: v.testCaseId, testCaseVersionId: v.id }); return { versionId: id, status: 'succeeded', membership: { testCaseId: v.testCaseId, testCaseVersionId: v.id } }; } catch (error) { return { versionId: id, status: 'other validation reason', reason: error instanceof Error ? error.message : String(error) }; } }); this.suiteMembership.set(suiteId, members); return results; }
  assertCaseProject(testCaseId: string, projectId: string): void { const tc = this.cases.get(testCaseId); if (!tc) throw new Error(`Test case ${testCaseId} not found`); if (tc.projectId !== projectId) throw new Error('Forbidden for this project'); }
  assertVersionProject(versionId: string, projectId: string): void { const v = this.getVersion(versionId); this.assertCaseProject(v.testCaseId, projectId); }
  coverage(projectId: string, scope: CoverageScope = {}) { const versions = this.reviewQueue(projectId).map((x) => x.version); const summary = calculateCoverage(versions, scope); const unique = (items: unknown[]) => new Set(items.filter(Boolean) as any[]).size; const strategies = versions.map((v) => (v.content.mutationProvenance as any)?.strategy); return { ...summary, testCases: versions.length, acceptanceCriteriaCovered: unique(versions.map(v => v.content.acceptanceCriterionId)), operationsCovered: unique(versions.map(v => v.content.operationId)), schemaParametersCovered: unique(versions.map(v => (v.content.mutationProvenance as any)?.fieldPath)), requiredFieldCoverage: strategies.filter(s => s === 'required-field').length, boundaryNegativeRuleCoverage: strategies.filter(s => ['boundary', 'type-violation', 'enum-violation', 'format-violation'].includes(s)).length, mutationStrategies: [...new Set(strategies.filter(Boolean))] }; }
  diff(leftVersionId: string, rightVersionId: string) { const left = this.getVersion(leftVersionId).content as any; const right = this.getVersion(rightVersionId).content as any; return ['mapping', 'payload', 'assertions', 'mutationProvenance', 'generationProvenance', 'requirementId', 'acceptanceCriterionId', 'generatedContent'].filter((field) => JSON.stringify(left[field]) !== JSON.stringify(right[field])).map((field) => ({ field, before: left[field], after: right[field] })); }
  private reviewView(version: TestCaseVersionEntity) { const c: any = version.content; return { scenarioIntent: c.scenarioIntent, requirementId: c.requirementId, acceptanceCriterionId: c.acceptanceCriterionId, operation: { id: c.operationId, label: c.operationLabel || c.operationId, protocol: c.protocol || 'generic', risk: c.operationRisk || 'unknown' }, mapping: c.mapping, mutationProvenance: c.mutationProvenance, baselineInput: c.baselineInput, mutatedInput: c.payload, assertions: c.assertions, currentVersion: version.version, reviewStatus: version.lifecycle }; }
  private newVersion(testCaseId: string, version: number, content: TestCaseVersionContent, lifecycle: TestCaseLifecycle) { const entity = new TestCaseVersionEntity(randomUUID(), testCaseId, version, structuredClone(content), lifecycle, Date.now()); if (!entity.content.coverage) (entity.content as any).coverage = calculateCoverage([entity]); return entity; }
  private withoutCoverage(content: TestCaseVersionContent) { const { coverage: _coverage, ...stable } = content; return stable; }
  private restore(): void { if (!this.storagePath || !existsSync(this.storagePath)) return; try { const data = JSON.parse(readFileSync(this.storagePath, 'utf8')); for (const item of data.cases || []) this.cases.set(item.id, new TestCaseEntity(item.id, item.projectId, item.fingerprint, item.currentVersionId, item.createdAt, item.updatedAt)); for (const item of data.versions || []) this.versions.set(item.id, new TestCaseVersionEntity(item.id, item.testCaseId, item.version, item.content, item.lifecycle, item.createdAt, item.reviewer, item.reviewedAt, item.reviewReason)); } catch { throw new Error('Test case version storage is invalid; restore it before starting TestForge'); } }
  private persist(): void { if (!this.storagePath) return; mkdirSync(dirname(this.storagePath), { recursive: true }); writeJsonFileSyncAtomic(this.storagePath, { cases: [...this.cases.values()], versions: [...this.versions.values()] }); }
}
