import { describe, expect, it, vi } from 'vitest';
import { DurableJobWorker } from './DurableJobWorker.js';
import { newJob } from '../../infrastructure/jobs/JsonDurableJobRepository.js';

function repo(job: any) { return { claim: vi.fn().mockResolvedValue(job), renewLease: vi.fn().mockResolvedValue(job), updatePayload: vi.fn(async (_id:string,_worker:string,payload:any) => { job.payload = payload; return job; }), findById: vi.fn().mockResolvedValue(job), acknowledge: vi.fn().mockResolvedValue(job), fail: vi.fn().mockResolvedValue(job) }; }
const job = () => newJob({ projectId:'p', jobType:'SUITE_EXECUTION', payload:{suiteId:'suite',environmentId:'env',executionProfileId:'profile'}, createdBy:'scheduler',maxAttempts:2,idempotencyKey:'key' });
describe('DurableJobWorker', () => {
  it('reuses ExecuteSuite and propagates environment/profile', async () => { const j:any=job(); const r=repo(j); const execute=vi.fn().mockResolvedValue({id:'run-1'}); const w=new DurableJobWorker(r as any,{execute} as any); await w.workOnce(); expect(execute).toHaveBeenCalledWith('suite',undefined,'profile','env'); expect(r.updatePayload).toHaveBeenCalledWith(j.jobId,w.workerId,expect.objectContaining({executionRunId:'run-1'})); expect(r.acknowledge).toHaveBeenCalledWith(j.jobId,w.workerId); });
  it('acknowledges a reclaimed job already linked to a run without executing again', async () => { const j:any=job(); j.payload.executionRunId='run-1'; const r=repo(j); const execute=vi.fn(); const w=new DurableJobWorker(r as any,{execute} as any); await w.workOnce(); expect(execute).not.toHaveBeenCalled(); expect(r.acknowledge).toHaveBeenCalled(); });
  it('does not create another ExecutionRun after a crash/reclaim once the link is persisted', async () => { const j:any=job(); const r=repo(j); const execute=vi.fn().mockResolvedValue({id:'run-1'}); const w=new DurableJobWorker(r as any,{execute} as any); await w.workOnce(); await w.workOnce(); expect(execute).toHaveBeenCalledTimes(1); expect(r.acknowledge).toHaveBeenCalledTimes(2); });
  it('records safety failures through durable retry handling with sanitized metadata', async () => { const j:any=job(); const r=repo(j); const w=new DurableJobWorker(r as any,{execute:vi.fn().mockRejectedValue(new Error('Execution safety blocked: token=secret'))} as any); await w.workOnce(); expect(r.fail).toHaveBeenCalledWith(j.jobId,w.workerId,expect.objectContaining({message:expect.stringContaining('Execution safety blocked')})); });
  it('does not mark a running job successful after it is cancelled', async () => { const j:any=job(); const r=repo(j); r.findById.mockResolvedValue({ ...j, status:'CANCELLED' }); const w=new DurableJobWorker(r as any,{execute:vi.fn().mockResolvedValue({id:'run-1'})} as any); await w.workOnce(); expect(r.acknowledge).not.toHaveBeenCalled(); expect(r.fail).not.toHaveBeenCalled(); });
  it('graceful shutdown prevents new claims', async () => { const r=repo(job()); const w=new DurableJobWorker(r as any,{execute:vi.fn()} as any); await w.stop(); await w.workOnce(); expect(r.claim).not.toHaveBeenCalled(); });
});
